name: release

env:
  GO_VERSION: '1.23'

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.sum

      - name: Extract version from tag
        id: vars
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Compute artifact name
        id: name
        run: |
          echo "filename=tfs-${{ steps.vars.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}" >> $GITHUB_OUTPUT

      - name: Build binaries
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          go build -o build/tfs

      - name: Archive binaries
        run: |
          mkdir -p dist
          filename="${{ steps.name.outputs.filename }}"
          tar -czf "dist/${filename}.tar.gz" -C build tfs
          zip -j "dist/${filename}.zip" build/tfs

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
